package main

import (
	_ "backend/docs" // Import the docs generated by Swag
	"backend/routes"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	r := gin.Default()

	// Register your login route
	routes.AuthRoutes(r)

	// Register Swagger UI route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	r.Run(":8080") // Or any other port you're using
}
